defaults:
  - agent: generalist
  - evolution: progressive
  - _self_

results:
  lines_filename: "${agent.image_folder}line_plots_e${environment.enemies}.png"

nn:
  n_hidden: 10

compare:
  n_sim: 10
  n_gens: 40
  evo1: fps
  evo2: mcs

train:
  n_gens: 40
  evo: ${evolution.create}

environment:
  name: "environment_${agent.type}"
  enemies: ???

