defaults:
  - agent: generalist
  - evolution: progressive
  - _self_

nn:
  n_hidden: 10

simulation:
  n_sim: 10
  n_gens: 40
  evolutions:
    - fps
    - mcs

train:
  n_gens: 40
  evolution: ${evolution.create}

environment:
  name: "environment_${agent.type}"
  enemies: ???

