defaults:
  - agent: generalist
  - _self_

nn:
  n_hidden: 10

simulation:
  n_sim: 10
  n_gens: 40
  evolutions:
    - adaptive
    - progressive

environment:
  name: "environment_${agent.type}"
  enemies: ???

