defaults:
  - config
  - evolution: adaptive
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

_evolution: ${evolution.create}

n_gens: 40

hydra:
  sweeper:
    sampler:
      seed: 1234
    direction: maximize
    study_name: train
    storage: null
    n_trials: 100
    n_jobs: 1
    params:
      evolution.create.params.learning_rate: range(0.16, 0.26, 0.005)
      evolution.create.params.beta: range(0.5, 1,5, 0.1)
