defaults:
  - config
  - evolution: progressive
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

hydra:
  sweeper:
    sampler:
      seed: 1234
    direction: maximize
    study_name: train
    storage: null
    n_trials: 100
    n_jobs: 1
    params:
      train.n_gens: 50
      evolution.create.params.pop_size: 100
      evolution.create.params.alpha: range(0.2, 0.8, 0.05)
      evolution.create.params.beta: range(0.2, 0.8, 0.05)
      environment.enemies: choice("127", "78")