defaults:
  - config
  - evolution: progressive
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

_evolution: ${evolution.create}

n_gens: 40

hydra:
  sweeper:
    sampler:
      seed: 1234
    direction: maximize
    study_name: train
    storage: null
    n_trials: 100
    n_jobs: 1
    params:
      evolution.create.params.alpha: range(0.95, 1.4, 0.1)
      evolution.create.params.beta: range(0.5, 1.5, 0.1)
