defaults:
  - base
  - _self_

create:
  _target_: evolution.adaptive.Adaptive

  params:
    # offspring related params
    lambda_0: 1
    a: 1
    b: 2

    # mutation related params
    mutation_prob: 1
    learning_rate: 0.25
    epsilon_0: 0.1
