defaults:
  - base
  - _self_

create:
  _target_: evolution.self_adaptive.SelfAdaptive

  params:
    # offspring related params
    lambda_0: 0.8
    a: 1.5
    b: 3

    # mutation related params
    mutation_prob: 1
    learning_rate: 0.25
    epsilon_0: 0.1
